name: daily-update
on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  scrape-job:
    runs-on: ubuntu-latest
    permissions: { contents: write }
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      
      - name: Install dependencies
        run: pip install requests django djangorestframework

      - name: Scrape Ratings
        run: python -m players.update_ratings
        working-directory: backend 
        env:
          PYTHONPATH: .

      - name: Commit and Push CSV to GitHub
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add backend/players/players.csv
          git commit -m "Automated update" || echo "No changes to commit"
          git push

      - name: Sync to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add hf https://redcomp16:$HF_TOKEN@huggingface.co/spaces/redcomp16/checkchesser-backend
          git push hf main --force
