name: daily-update
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  scrape-job:
    runs-on: ubuntu-latest
    permissions: { contents: write }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      
      - name: Install dependencies
        run: pip install requests django djangorestframework

      - name: Scrape Ratings
        run: python update_ratings.py

      - name: Commit and Push CSV
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add backend/players/players.csv
          git commit -m "Automated update" || exit 0
          git push

      - name: Reload PythonAnywhere
        run: |
          curl -X POST "https://www.pythonanywhere.com/api/v1/user/redcomp16/webapps/redcomp16.pythonanywhere.com/reload/" \
            -H "Authorization: Token ${{ secrets.PA_TOKEN }}"
